### ISSUE TITLE
License complaint?

### ISSUE THREAD

**Issue by leonardp** [kost/webrepl-python#1]
Hi,

first of thanks for putting in effort on this project. It works nicely.
But I think you should add the following lines to your License:
```
Copyright (c) 2016 Damien P. George
Copyright (c) 2016 Paul Sokolovsky
```
since it seems to be a derivative of [micropython's webrepl](https://github.com/micropython/webrepl).
I do not know if it strictly required by the MIT license to do that, even if it isn't I think it would be good practice to do it anyway.

**Comment by kost** [comment]
Agree. Credits should given nevertheless.

Should have done that earlier, but was up to speed to work for me.

Added in README and LICENSE.

Fixed in c419d90df67229fe591067de5a39a05946f2b99f
